import './globals.css'
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <header className='header'>
          <nav className="nav-list">
            <Link className="nav-list-item is-active" href="/">Home</Link>
            <Link className="nav-list-item" href="/products">Products</Link>
          </nav>
        </header>
        
      {children}
      </body>
    </html>
  )
}
